server:
  port: 8084

spring:
  application:
    name: linkflow-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linkflow_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linkflow.user.model

# Dubbo 配置
dubbo:
  application:
    name: linkflow-user
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    parameters:
      namespace: linkflow
  protocol:
    name: dubbo
    port: 20884
  scan:
    base-packages: com.linkflow.user.service