server:
  port: 8084

spring:
  application:
    name: linkflow-campaign
  datasource:
    url: jdbc:mysql://localhost:3306/short_link_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: record

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linkflow.campaign.model

# Dubbo 配置
dubbo:
  application:
    name: linkflow-campaign
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    parameters:
      namespace: linkflow
      register-consumer-url: true
  protocol:
    name: dubbo
    port: 20884
    host: ${DUBBO_HOST:10.250.246.71}
  scan:
    base-packages: com.linkflow.campaign.service

linkflow:
  campaign:
    kafka:
      topics:
        campaign-approved: campaign.approved
      consumer-group: linkflow-campaign-shortlink
